// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// always-run-in-app: true; icon-color: deep-brown;
// icon-glyph: magic; share-sheet-inputs: plain-text, image, url, file-url;
var gameNiche;
gameNiche;
var gamePatch;
gamePatch;
var patchEnglewood;
patchEnglewood;
var patchAustin;
patchAustin;
var patchMillenneumPark;
patchMillenneumPark;
var patchUptown;
patchUptown;
var nicheTragedyCommomsBar;
nicheTragedyCommomsBar;
var resourcePublicNuisanceCityTaste;
resourcePublicNuisanceCityTaste;
var nicheSophoclesBar;
nicheSophoclesBar;
var nicheHazardousDutyBar;
nicheHazardousDutyBar;
var nichePigBar;
nichePigBar;
var resourceDepletion;
resourceDepletion;
var playerDesertion;
playerDesertion;
var playerScore;
playerScore;
var scoreQOL;
scoreQOL;
var gameQOL;
gameQOL;
var qolFitness;
qolFitness;
var qolForaging;
qolForaging;
var qolResources;
qolResources;
var fitnessBMIScore;
fitnessBMIScore;
var gameMassBodyIndex;
gameMassBodyIndex;
